### ISSUE TITLE
Sonarqube 8.9 fails to start 

### ISSUE THREAD

**Issue by ebennett98** [CreditMutuelArkea/sonar-apigee-plugin#11]
I have tried to add this plugin 4.1.0 to my recently upgraded sonarqube server 8.0 to 8.9 and when I add this plugin jar to the directory sonarqube will not start, it seems to be an elasticsearch issue. Sonarqube advised to reach out here.

**Comment by ntiss** [comment]
Hello @ebennett98 
Indeed, good advice from Sonarqube and its community.
Thanks for reporting this issue. I'll give you an update as soon as I'm able to reproduce or publish a fix.

**Comment by ntiss** [comment]
Hello @ebennett98  ,

Indeed, I can easily reproduce the issue. The problem is due to the latest version of the sonar-xml plugin that is brought with SonarQube 8.8+. So the sonar-apigee-plugin needs some refactoring in order to become compatible with sonar-xml 2.1 or 2.2.

In the meantime, I can suggest these 2 workarounds :
First: the awful ugly option NOT RECOMMENDED, NOT SUPPORTED: replace the file `${sonar.home}/lib/extensions/sonar-xml-plugin-2.1.0.2861.jar` (or `sonar-xml-plugin-2.2.0.2973.jar`) with the `sonar-xml-plugin-2.0.1.2020.jar` found on Github. Tested on SQ 8.8, seems to work, no warranty, do not try this in production !

Or, prefered recommendation: do not upgrade and stay with SQ 8.7.1 while I work on a new release (ETA: couple of days or weeks). SQ 8.7.1 is the last version on which the plugin is natively supported.

Regards.

**Comment by agigleux** [comment]
Hello,

Waiting for the fix to be ready, I temporarily marked the plugin as not compatible with SQ 8.9 LTS. (I will also remove 8.8).
Please ping me here once the version compatible with SQ 8.9 LTS is available and I'll revert my commit.

Thanks
Alex (PM @ SonarSource)

**Comment by ntiss** [comment]
Hi @agigleux 
Thanks for your action on `sonar-update-center-properties/apigee.properties`
I'm currently working on the 3.0.0 release. Almost finished.
The fix will be ready soon with an announcement on [SQ Community Forum](https://community.sonarsource.com/c/plugins/15) and PR on [sonar-update-center-properties](https://github.com/SonarSource/sonar-update-center-properties)

Regards,
Nicolas (plugin author)

**Comment by ntiss** [comment]
Hi @agigleux 
Release 3.0.0 is out.
The announce is [here in the SQ Community Forum](https://community.sonarsource.com/t/new-release-sonar-apigee-plugin-3-0-0/43932)

**Comment by agigleux** [comment]
Looks like you changed a dependency to the XML Plugin and this prevents to update the Marketplace:

`The plugin 'xml' is in version 2.0.1 whereas the plugin 'apigee' requires a least a version 2.1.0`

**Comment by agigleux** [comment]
I can't it to the Marketplace for the moment probably linked to the fact that embedded analyzers provided by default with SonarQube are now no longer in the Marketplace:

`Fail to execute mojo: The plugin 'xml' is in version 2.0.1 whereas the plugin 'apigee' requires a least a version 2.1.0`

**Comment by agigleux** [comment]
@ntiss Can you remove this [line](https://github.com/CreditMutuelArkea/sonar-apigee-plugin/blob/master/pom.xml#L140) and do a 3.0.1 release. It's no longer required because now with SQ 8.8+ the XML Analyzer is provided by default with SonarQube.

**Comment by ntiss** [comment]
3.0.1 is out, it should be bette now.
New PR here :[https://github.com/SonarSource/sonar-update-center-properties/pull/220]( https://github.com/SonarSource/sonar-update-center-properties/pull/220)
I've also updated the announcement on the SQ Forum.

**Comment by ntiss** [comment]
Hello @ebennett98 
This issue is now fixed by the publication of the release 3.0.1.
My apologies for the outage. Thanks for reporting it.

**Comment by chbieri** [comment]
Still got an exception and startup failed, after upgrade sonarqube 8.6 to 8.9 with the latest available apigee Version 2.1.1 under sonarqube 8.6.

`2021.07.12 08:08:36 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.NoSuchMethodError: 'void org.sonarsource.analyzer.commons.RuleMetadataLoader.<init>(java.lang.String, java.lang.String, org.sonar.api.SonarRuntime)'
        at com.arkea.satd.sonar.xml.ApigeeXmlRulesDefinition.define(ApigeeXmlRulesDefinition.java:39)
        at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:53)
        at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:117)
        at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
        at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
        at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
        at org.picocontainer.behaviors.Stored.start(Stored.java:110)
        at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
        at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
        at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:49)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:87)
        at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:45)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:84)
        at org.sonar.server.platform.PlatformImpl.executeStartupTasks(PlatformImpl.java:198)
        at org.sonar.server.platform.PlatformImpl.access$400(PlatformImpl.java:46)
        at org.sonar.server.platform.PlatformImpl$1.lambda$doRun$1(PlatformImpl.java:122)
        at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:370)
        at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:122)
        at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:354)
        at java.base/java.lang.Thread.run(Unknown Source)`

We work around by uninstall the plugin before upgrade and reinstall afterwards.

**Comment by ntiss** [comment]
Hi @chbieri 
You're right, it seems that there is no solution to upgrade Sonarqube with this plugin installed because the dependence "sonar-xml" is now built-in in QS. So, during the upgrade, there is a moment where the apigee plugin is not compatible.

Your suggestion is the good one : uninstall the plugin before upgrade and reinstall afterwards.
Thanks.
